Efficiency fix on versions below 1.13
PrismarineJS/prismarine-block pull request #23
Opened 2021-02-23 17:54 UTC by goncharovchik

2021-02-23 18:49 UTC, Karang requested changes
One comment, otherwise LGTM, thanks!

2021-02-23 18:49 UTC, Karang commented on index.js
> +  Block.prototype.digTime = function (heldItemType, creative, inWater, notOnGround, enchantments = [], effects = {}, version) {
You don't have to give the version, you can use `majorVersion` instead (defined here https://github.com/PrismarineJS/prismarine-block/blob/e88ba1ebd5d3f775b51322b4f03e4309a9024622/index.js#L17). That should remove the breaking change.

2021-02-23 19:33 UTC, rom1504 approved these changes

2021-02-28 22:33 UTC, rom1504 approved these changes

2021-02-28 22:33 UTC, merged